name: Publish
on:
  push:
    branches:
      - production

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest

    name: Publish
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Yarn Install
        run: yarn install --network-concurrency 1

      - name: Build
        run: yarn prod

      - name: Publish (NPM)
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish (GPR)
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: vars
        run: echo version="$(jq -r ".version" package.json)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          name: ${{ steps.vars.outputs.version }}
          tag_name: v${{ steps.vars.outputs.version }}
          generate_release_notes: true
